### ISSUE TITLE
[BUG] hashInUri on Windows

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#232]
`hashInUri` fail randomly on Windows 

```
echo: http: panic serving [::1]:63819: runtime error: index out of range [-724]
goroutine 34 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1850 +0xe0
panic({0xcb6fe0, 0x13b01ab0})
        /usr/local/go/src/runtime/panic.go:890 +0x21a
github.com/cgi-fr/pimo/pkg/hash.MaskEngine.Mask({{0x1386a000, 0x375, 0x375}}, {0xc65f60, 0x13c2e8e8}, {0x1388cdf8, 0x2, 0x2})
        /workspace/pkg/hash/hash.go:48 +0x145
github.com/cgi-fr/pimo/pkg/model.(*MaskEngineProcess).ProcessDictionary.func2({0x13b11500}, {0x13b11500}, {0x13b01468, 0x4}, {0xc65f60, 0x13c2e8e8})
        /workspace/pkg/model/process_mask.go:54 +0x29d
github.com/cgi-fr/pimo/pkg/model.selector.apply({{0x13b01468, 0x4}, {0x0, 0x0}}, {0x13b11500}, {0x13b11500}, {0xc65f60, 0x13c2e8e8}, {0x1388cdd0, 0x1, ...})
        /workspace/pkg/model/selector.go:143 +0x6e
github.com/cgi-fr/pimo/pkg/model.selector.applySub({{0x13b01468, 0x4}, {0x0, 0x0}}, {0x13b11500}, {0x13b11500}, {0x1388cdd0, 0x1, 0x1})
        /workspace/pkg/model/selector.go:136 +0x1d7
github.com/cgi-fr/pimo/pkg/model.selector.Apply(...)
        /workspace/pkg/model/selector.go:84
github.com/cgi-fr/pimo/pkg/model.(*MaskEngineProcess).ProcessDictionary(0x1396c630, {0x13b11500}, {0x13e4e34, 0x13b114c0})
        /workspace/pkg/model/process_mask.go:45 +0x1d0
github.com/cgi-fr/pimo/pkg/model.(*ProcessPipeline).Next(0x13b1ada0)
        /workspace/pkg/model/model.go:553 +0xe3
github.com/cgi-fr/pimo/pkg/model.SimpleSinkedPipeline.Run({{0x13e8500, 0x13b1ada0}, {0x13e7454, 0x13b114e0}})
        /workspace/pkg/model/model.go:601 +0x15e
github.com/cgi-fr/pimo/internal/app/pimo.(*Context).Execute(0x13a75a54, {0x13e5514, 0x13b114d0})
        /workspace/internal/app/pimo/pimo.go:176 +0x3f1
github.com/cgi-fr/pimo/internal/app/pimo.play({0x13ea300, 0x138b6000})
        /workspace/internal/app/pimo/play.go:102 +0x707
github.com/labstack/echo/v4.(*Echo).add.func1({0x13ea300, 0x138b6000})
        /home/vscode/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/echo.go:536 +0x4c
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x13ea300, 0x138b6000})
        /home/vscode/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/middleware/logger.go:119 +0xed
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x13ea300, 0x138b6000})
        /home/vscode/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/middleware/cors.go:255 +0x8ce
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x13804280, {0x13e80c8, 0x138b0280}, 0x13896380)
        /home/vscode/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/echo.go:646 +0x3a6
net/http.serverHandler.ServeHTTP({0x138021e0}, {0x13e80c8, 0x138b0280}, 0x13896380)
        /usr/local/go/src/net/http/server.go:2947 +0x285
net/http.(*conn).serve(0x13b0e000, {0x13e8440, 0x1396c270})
        /usr/local/go/src/net/http/server.go:1991 +0x67d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x498
```

**Comment by adrienaury** [comment]
seems to be ok on PIMO 1.26.0
