### ISSUE TITLE
bug: jsonpath to array component not working

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#3]
**data.jsonl**
```json
{"elements":[{"persons": [{"phonenumber": "027"}]}]}
```

 **masking.yml**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "elements.persons.phonenumber"
    mask:
      regex: "0[1-7]( ([0-9]){2}){4}"
```

 **Result**
```console
$ pimo <data.jsonl >dataout.jsonl

panic: interface conversion: model.Entry is []model.Entry, not map[string]model.Entry

goroutine 1 [running]:
makeit.imfr.cgi.com/makeit2/scm/lino/pimo/pkg/model.ComplexePathSelector.Write(0xc00002c8a9, 0x7, 0x92c978, 0xc00001f730, 0xc0001ba300, 0x80e3e0, 0xc00001f7d0, 0xc00011dc20)
        /workspace/pkg/model/model.go:308 +0x6c5
makeit.imfr.cgi.com/makeit2/scm/lino/pimo/pkg/model.ComplexePathSelector.Write(0xc00002c8a0, 0x8, 0x92c938, 0xc00006e840, 0xc0001ba360, 0x807240, 0xc00000c870, 0xc00000c870)
        /workspace/pkg/model/model.go:302 +0x2de
makeit.imfr.cgi.com/makeit2/scm/lino/pimo/pkg/model.(*MaskEngineProcess).ProcessDictionary(0xc00006e880, 0xc0001ba360, 0x924260, 0xc00006e8a0, 0x0, 0x0)
        /workspace/pkg/model/model.go:460 +0x2dc
makeit.imfr.cgi.com/makeit2/scm/lino/pimo/pkg/model.(*ProcessPipeline).Next(0xc0000367c0, 0x0)
        /workspace/pkg/model/model.go:606 +0x96
makeit.imfr.cgi.com/makeit2/scm/lino/pimo/pkg/model.SimpleSinkedPipeline.Run(0x92bc50, 0xc0000367c0, 0x927e40, 0xc00001f740, 0x927e40, 0xc00001f740)
        /workspace/pkg/model/model.go:648 +0x89
main.run()
        /workspace/cmd/pimo/main.go:127 +0x65b
main.main.func1(0xc000128840, 0xba2298, 0x0, 0x0)
        /workspace/cmd/pimo/main.go:76 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000128840, 0xc00001e210, 0x0, 0x0, 0xc000128840, 0xc00001e210)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000128840, 0xb71910, 0x89c08d, 0xa)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/cmd/pimo/main.go:86 +0x433
```

**Comment by adrienaury** [comment]
### **Primary analysis**

Problem appear only on **nested** arrays.

Using this input json:

```yaml
[08:30] Aury, Adrien
    ce sont des logs pour traiter cet input : 
{​​​​​​
    "elements": [
        {​​​​​​
            "persons": [
                {​​​​​​
                    "phonenumber": "027123456"
                }​​​​​​,
                {​​​​​​
                    "phonenumber": "028123456"
                }​​​​​​
            ]
        }​​​​​​,
        {​​​​​​
            "persons": [
                {​​​​​​
                    "phonenumber": "029123456"
                }​​​​​​,
                {​​​​​​
                    "phonenumber": "020123456"
                }​​​​​​
            ]
        }​​​​​​
    ]
}​​​​​​
```

The matching values given by `mp.selector.Read(dictionary)` is  `[[027123456 028123456] [029123456 020123456]]` which is correct.

Then the masking process of theses values results to `[1 2]` which is **incorrect**.

The masking process should return an nested array with the same topology as the matching values i.e. `[[1 2] [3 4]`

**Comment by adrienaury** [comment]
**Additional analysis**

The `func (s ComplexePathSelector) Write` is not currently able to handle nested masked values.

If passed with a masked entry `[[1 2] [3 4]]` the type check on this entry will not detect it as a slice value.

```go
switch typedMatch := entry.(type) {
	case []Entry:
         // this will not match [[1 2] [3 4]] because it is not a []Entry type
        default:
        // therefore the default will be triggered, incorrectly
```

The correct way to handle the masked entry `[[1 2] [3 4]]` is with a `reflect.ValueOf(entry)` test :

```go
	v := reflect.ValueOf(entry)
	switch v.Kind() {
	case reflect.Slice:
		// this is a slice of something
		subTargetArray, isArray := result[s.path].([]Entry)
		if !isArray {
			result[s.path] = s.subSelector.Write(result[s.path].(Dictionary), entry)
		} else {
			subArray := []Dictionary{}
			for i := 0; i < v.Len(); i++ {
				subArray = append(subArray, s.subSelector.Write(subTargetArray[i].(Dictionary), v.Index(i).Interface()))
			}
			result[s.path] = subArray
		}

	default:
		// this is something else
		result[s.path] = s.subSelector.Write(result[s.path].(Dictionary), entry)
```
